version: "3.7"
services:
  ldap-pw-check:
    image: ldap-pw-check:0.3
    build: .
    container_name: ldap-pw-check
    restart: unless-stopped
    volumes:
      - ./log:/app/log
      - type: bind
        source: ./log.conf
        target: /etc/logrotate.d/log.conf
        read_only: yes

